_core:
  default_config_hash: Sd_9jXBxw3mGn9d_y94jvlitI0wpvj6x2dQ0p6aGhJo
entity_config:
  block_content:
    basic:
      enabled: true
      query_load_enabled: true
      edges_enabled: true
      routes_enabled: true
  image_style:
    1x1_third:
      enabled: false
    media_library:
      enabled: true
    thumbnail:
      enabled: true
  media:
    document:
      enabled: true
      query_load_enabled: true
      edges_enabled: true
      routes_enabled: true
    image:
      enabled: true
      query_load_enabled: true
      edges_enabled: true
      routes_enabled: true
    remote_video:
      enabled: true
      query_load_enabled: true
      edges_enabled: true
      routes_enabled: true
    video:
      enabled: true
      query_load_enabled: true
      edges_enabled: true
      routes_enabled: true
  menu:
    account:
      enabled: false
    admin:
      enabled: false
    footer:
      enabled: false
    main:
      enabled: false
    tools:
      enabled: false
  node:
    agency:
      enabled: true
      query_load_enabled: true
      edges_enabled: true
      routes_enabled: true
    article:
      enabled: false
    division:
      enabled: true
      query_load_enabled: true
      edges_enabled: true
      routes_enabled: true
    goal:
      enabled: true
      query_load_enabled: true
      edges_enabled: true
      routes_enabled: true
    objective:
      enabled: true
      query_load_enabled: true
      edges_enabled: true
      routes_enabled: true
    page:
      enabled: false
    plan:
      enabled: true
      query_load_enabled: true
      edges_enabled: true
      routes_enabled: true
    report:
      enabled: true
      query_load_enabled: true
      edges_enabled: true
      routes_enabled: true
  storage:
    administration:
      enabled: false
    indicator:
      enabled: true
    measurement:
      enabled: true
    period:
      enabled: true
    person:
      enabled: false
  taxonomy_term:
    tags:
      enabled: true
      query_load_enabled: true
      edges_enabled: true
      routes_enabled: true
    topics:
      enabled: true
      query_load_enabled: true
      edges_enabled: true
      routes_enabled: true
  user:
    user:
      enabled: false
field_config:
  media:
    document:
      field_media_document:
        enabled: true
    image:
      field_media_image:
        enabled: true
    remote_video:
      field_media_oembed_video:
        enabled: true
    video:
      field_media_video_file:
        enabled: true
  node:
    agency:
      body:
        enabled: true
      field_acronym:
        enabled: true
      field_link:
        enabled: true
      field_logo:
        enabled: true
    goal:
      body:
        enabled: true
      field_goal_type:
        enabled: true
      field_id:
        enabled: true
        name_sdl: fieldId
      field_objectives:
        enabled: true
      field_period:
        enabled: true
      field_plan:
        enabled: true
      field_topics:
        enabled: true
    objective:
      body:
        enabled: true
      field_agency:
        enabled: true
      field_division:
        enabled: true
      field_goal:
        enabled: true
      field_indicators:
        enabled: true
      field_objective_type:
        enabled: true
    plan:
      body:
        enabled: true
      field_administration:
        enabled: true
      field_agency:
        enabled: true
      field_date:
        enabled: true
      field_division:
        enabled: true
      field_file:
        enabled: true
      field_goals:
        enabled: true
      field_link:
        enabled: true
      field_period:
        enabled: true
    report:
      body:
        enabled: true
      field_file:
        enabled: true
      field_goals:
        enabled: true
      field_link:
        enabled: true
      field_period:
        enabled: true
      field_plan:
        enabled: true
  storage:
    indicator:
      field_description:
        enabled: true
      field_dimension:
        enabled: true
      field_divisions:
        enabled: true
      field_id:
        enabled: true
      field_keyness:
        enabled: true
      field_measurements:
        enabled: true
      field_notes:
        enabled: true
      field_objective:
        enabled: true
      field_plan:
        enabled: true
      field_target:
        enabled: true
    measurement:
      field_indicator:
        enabled: true
      field_period:
        enabled: true
      field_target_value:
        enabled: true
      field_value:
        enabled: true
    period:
      field_date_range:
        enabled: true
      field_duration:
        enabled: true
settings:
  exclude_unpublished: true
  expose_entity_ids: false
  field_required_override: false
  schema_description: 'GraphQL Compose'
  schema_version: '1'
  simple_queries: true
  simple_unions: true
  site_name: false
  site_slogan: false
  site_front: true
  svg_image: false
  svg_filesize: 100
  inflector_langcode: en
  inflector_singularize: true
  edge_max_limit: 100
